### PR TITLE
Beta fixes :

### PR DESCRIPTION
**Pull request by MadeInLithuania**
List of fixes : 

**Overall :**

1. Added navigation bar and edits
2. Responsive navigation menu for mobile users
3. Compatibility fixes (partial)
4. Added JavaScript and JQuery

**faq.html :**
1. Fixed the list

### CODE REVIEW

**Comment by MadeInLithuania** [comment]
:trollhd: waiting for fix

**Comment by Warriorrrr** [comment]
any day now

**Comment by MadeInLithuania** [comment]
@FixTheAdmin waiting :trollface:

**Comment by DasCodes** [comment]
I'll merge it, but I should state that we are no longer using this repo as we moved to WordPress.

**Pull request merged**
