### PR TITLE
Added responsiveness to the navigation bar

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Just in case you missed this one. You can check the demo [here](https://cloakedeagle.github.io/EarthMC.net/).

**Comment by KarlOfDuty** [comment]
The menu bar gets duplicated when adjusting window size

**Comment by ghost** [comment]
I noticed that, but I don't think that will be an issue though. As players won't be resizing their window most likely. But I'll try to fix it anyway, as it's bugging me. Any suggestion?

**Comment by KarlOfDuty** [comment]
I have no idea how any of this works but shouldn't you just be able to hide both the button and the new menu bar when the window is expanded?

**Comment by ghost** [comment]
🤔 Okay, I'll get on this fix.

**Pull request merged**
