### PR TITLE
Rule updates

### LINKED ISSUE #141: 3.3 Claim Blocking
**Exact wording of the rule**

**Before:**

3.3 Claim blocking.
“Claim blocking” is referring to the act of deliberately placing claims near a town in order to block its expansion. This includes placing a new town next to another with the intent of blocking their expansion.

 

A town's claims count as blocking if they create long arms of claims protruding from their town like in the images above. These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created.
 
Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it.

All claims which staff concludes to be blocking a town will be removed without any refund. Players found to be claim blocking more than once may be warned and denied the ability to place outposts all together.

**After:**

**3.3 Extreme Claim Blocking**
Extreme Claim Blocking is not allowed on EMC. Extreme claim blocking isn't limited to but includes: 
       Hollow Claiming.
       Claiming a town inside another town.
       Surrounding a town in claims.

For a claim block to be able to be reported the mayor of an affected town nearby must be the one to report it. Along with this the claim block but be preventing the expansion of nearby towns or preventing the creation of new towns. All claims which staff concludes to be blocking a town will be removed without any refund.

Claim Blocking is evaluated on a case by case basis and staff has final say in what is considered an extreme claim blocking. Players found to be claim blocking my be warned if there was an intent to cause harm through claim blocking.

**How will this rule affect the community**
This rule will help the community by allowing players to do more of what they want. This rule would only affect new claim blocking tickets after the rule goes in place. This will allow players to defend their own town better but also make sure the extremes dont ruin their playing experience. The claim blocking rule already doesn't get very enforced because everybody feels they are being claim blocked where in many instances they might not actually be. This causes both sides to get very upset and prevents anything from truly getting resolved

**Do you think this will benefit both the staff and the players**
Staff and players have to do claim blocking tickets as it is. The staff sometimes ignore the tickets do to their length and difficulty and the players get upset at that but also the outcome of the ticket often times. With a claim blocking ticket usually one of the parties will always be upset about the outcome and nothing truly gets resolved. With the rule set up like this less things will be considered against the rules which will generate less tickets and less people will get upset at the outcome of the tickets

### PR DESCRIPTION
**Pull request by KarlOfDuty**
Main change:
from
https://earthmc.net/rules.html#3.3
to
image

Closes #141

### CODE REVIEW

**Comment by jkmartindale** [comment]
What is this PR waiting on?

EDIT: Nevermind, I think it's waiting on translation

**Comment by KarlOfDuty** [comment]
No, I decided to make it public so players had a chance to comply to the new rules before they are in effect.

**Comment by coblobster2** [comment]
I like the change in ruling except for the hollowclaiming. I get it can help towns statistically but it also can help enforce border agreements. If you make a border agreement with someone and you don't want them to break it you can hollow claim so they can't and then you slowly fill it in. Or if you don't have plans to build somewhere just yet you claims around it until too u have a plan to save gold while not getting bored.

**Comment by MineHero43** [comment]
I think Hollow claims should be allowed unless a neighbouring town complains. A random town in the middle of nowhere with a couple hollow claims does no harm to anyone..

**Comment by DeadGlamour** [comment]
I feel major hollow claiming shouldnt be allowed, lets say if the hollow claim is more than 10% of the shown claim it should be removed, like a few chunks shouldnt be a problem, its only problematic when its large.

**Comment by coblobster2** [comment]
Yeah I said like 10 claims at most or something like that

**Comment by KarlOfDuty** [comment]
To answer some of the questions here, the moderators will likely not remove any hollow claims smaller than 4 chunks ish in size.

**Pull request merged**
