### PR TITLE
Added FAQ, updated rules page etc

### PR DESCRIPTION
**Pull request by ghost**
- Added FAQ
- Added normalize.css
- Added navigation bar on rules page
- Linked the logo to homepage

### CODE REVIEW

**Comment by FixTheAdmin** [comment]
Thanks for the pull request? What's up with the normielize.css dependency? <o/

**Comment by FixTheAdmin** [comment]
If there are any specific elements you want I'd rather have them added to the main css file to reduce number of requests

**Comment by ghost** [comment]
Normalize.css is just a CSS library which clears out the browser defaults, for better formatting with all browsers.
https://necolas.github.io/normalize.css/

**Comment by FixTheAdmin** [comment]
Ah right, sorry. I had it mixed up with materializecss.com.

**Comment by ghost** [comment]
I have added everything else in the main.css otherwise. Also didn't add the `iceroad` rule. So you'll have to write it :P.

And no worries :D

**Comment by KarlOfDuty** [comment]
Could you change the list items back to be indented? @CloakedEagle 

image

image

**Comment by ghost** [comment]
Done.

**Pull request merged**
