### PR TITLE
Some changes on FAQ

### PR DESCRIPTION
**Pull request by DasCodes**
- Moved favicon to main directory
- Added jQueryUI for better tooltip
- Added End rod recipe
- Formatted the recipe codes
- Moved nav function to main.js

### CODE REVIEW

**Comment by KarlOfDuty** [comment]
Could you fix that failing check first?

**Comment by DasCodes** [comment]
🤔 How did I not see that `else` block? I was writing a plugin where the images in the crafting boxes would animate, as some of the recipes can have multiple ways of crafting.

**Comment by DasCodes** [comment]
More updates will follow as soon as I get that piece of code working. 😅

**Review by KarlOfDuty — APPROVED** [review]

**Comment by DeadGlamour** [comment]
FAQ has outdated info about the channel system and atill says to use the old system, also there are recipes for lily pads and vines as well

**Comment by DasCodes** [comment]
> FAQ has outdated info about the channel system and atill says to use the old system, also there are recipes for lily pads and vines as well

They aren't outdated, the main commands are `/channel join town/nation`, and we do have alias commands for example `/tc` `/nc`. However, I think the alias commands are not working from time to time, which needs fixing. @DeadGlamour.

**Pull request merged**
