### PR TITLE
Translate all the pages to chinese. fixed some error words in rules_cn

### PR DESCRIPTION
**Pull request by SnUncle**

### CODE REVIEW

**Review by DasCodes — APPROVED** [review]

**Review by KarlOfDuty — CHANGES_REQUESTED** [review]
What is going on with the rules document there? It seems there are whitespace changes on every line.

**Comment by DasCodes** [comment]
I'm checking on that conflict.

**Comment by SnUncle** [comment]
rules doc or rules_cn？ was typed some whitespace to make the chinese contents look better

**Comment by KarlOfDuty** [comment]
Sure but the entire document is in the diff, should only be the lines you edited.

**Comment by KarlOfDuty** [comment]
Also, this has a bunch of commits that are already in the repo, not sure how that works.

**Comment by SnUncle** [comment]
Aight. i will double check it

**Comment by DasCodes** [comment]
Did you pull the changes that Karl had made last time before pushing the changes?

**Comment by SnUncle** [comment]
Yes,reforked whole docs

**Comment by DasCodes** [comment]
:harold:

**Review by DasCodes — CHANGES_REQUESTED** [review]
Still the whole file is conflicted.

**Comment by SnUncle** [comment]
Oh no

**Review by DasCodes — APPROVED** [review]

**Pull request merged**
